Category.create(name: 'Travel')
Category.create(name: 'Sport')
Category.create(name: 'Buy or Sell')
Category.create(name: 'Exchange')
Category.create(name: 'Recreation')
Category.create(name: 'Other')
